feat: new capsvr and kyc errors added
capitual/errors pull request #4
Opened 2022-01-14 21:16 UTC by andrerebonato

The title tells itself

2022-01-15 17:38 UTC, eduardoborges requested changes

2022-01-15 17:38 UTC, eduardoborges commented on package.json
> +  "version": "1.0.1",
Voce nao precisa alterar a versão, o semantic release gera com base nos commits. ;)

2022-01-17 13:54 UTC, andrerebonato commented on package.json
> +  "version": "1.0.1",
Removido

2022-01-17 13:54 UTC, DanielDDHM approved these changes

2022-01-17 13:54 UTC, viniciussiqueir4 approved these changes

2022-01-17 13:55 UTC, Bujira submitted a review, later dismissed

2022-01-17 13:56 UTC, DanielDDHM approved these changes

2022-01-17 13:56 UTC, Bujira approved these changes

2022-01-17 13:56 UTC, viniciussiqueir4 approved these changes

2022-01-17 14:04 UTC, Bujira approved these changes

2022-01-17 14:07 UTC, viniciussiqueir4 approved these changes

2022-01-17 14:09 UTC, DanielDDHM approved these changes

2022-01-17 14:10 UTC, eduardoborges requested changes

2022-01-17 14:10 UTC, eduardoborges commented on package.json
> -    "test:lint": "eslint src --ext .ts"
Aqui precisa ser `test:lint` mesmo, se nao o concurrently nao pega.

2022-01-17 14:14 UTC, eduardoborges requested changes

2022-01-17 14:14 UTC, eduardoborges commented on package.json
> +    "lint:fix": "eslint --ext js,ts src --fix"
```suggestion
    "test:lint": "npm run lint",
    "lint": "eslint --ext js,ts src",
    "lint:fix": "npm run lint -- --fix"
```

2022-01-17 14:18 UTC, DanielDDHM approved these changes

2022-01-17 14:18 UTC, eduardoborges approved these changes

2022-01-17 14:18 UTC, merged